name: Agent Runner

on:
  push:
    paths:
      - 'agent/tasks/queued/*.json'   # normal trigger: queue a task
      - 'agent/output.json'           # cleanup trigger on merges to main
  workflow_dispatch: {}               # manual trigger allowed

jobs:
  # =========================
  # 1) Run the agent on a task
  # =========================
  run-agent:
    if: github.event_name != 'push' || !endsWith(github.event.head_commit.message, 'cleanup-output')  # don't run on cleanup commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Prepare a fresh agent branch *before* running the bot,
      # so bot writes land directly on that branch.
      - name: Prepare agent branch
        id: prep
        run: |
          SAFE_NAME="$(test -f agent/last_branch_name.txt && cat agent/last_branch_name.txt || echo run)"
          SAFE_NAME="$(echo "$SAFE_NAME" | tr '[:space:]' '-' | tr -cd '[:alnum:]-_.')"
          BRANCH="agent-${SAFE_NAME}-${GITHUB_RUN_NUMBER}"

          git config user.name "agent-bot"
          git config user.email "bot@example.com"

          git fetch origin --prune
          git checkout -B "$BRANCH" origin/main

          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt

      - name: Run agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python agent/bot.py

      - name: Show repo tree after agent
        run: ls -R

      - name: Print agent outputs
        run: |
          echo "=== last_branch_name ==="
          cat agent/last_branch_name.txt || true
          echo "=== last_pr_body ==="
          cat agent/last_pr_body.txt || true
          echo "=== output.json ==="
          test -f agent/output.json && cat agent/output.json || echo "(no output.json)"

      - name: Commit changes (if any)
        id: commit
        run: |
          # Explicitly add output.json so it appears in PRs
          git add agent/output.json || true
          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          git commit -m "Agent: $(cat agent/last_branch_name.txt 2>/dev/null || echo update)"
          git push --set-upstream origin "${{ steps.prep.outputs.branch }}"
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Open Pull Request
        if: steps.commit.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Agent: $(cat agent/last_branch_name.txt 2>/dev/null || echo update)"
          body: |
            $(cat agent/last_pr_body.txt 2>/dev/null || echo "Agent update")
          branch: ${{ steps.prep.outputs.branch }}
          base: main

  # =======================================
  # 2) Auto-clean output.json from main
  #    (runs when output.json hits main)
  # =======================================
  cleanup-output-on-main:
    if: github.ref_name == 'main'    # only ever run this on pushes to main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove agent/output.json if present
        id: clean
        run: |
          if [ -f agent/output.json ]; then
            echo "output.json found on main — removing."
            git config user.name "agent-bot"
            git config user.email "bot@example.com"
            git rm -f agent/output.json
            git commit -m "cleanup-output: remove agent/output.json from main"
            git push
            echo "removed=true" >> $GITHUB_OUTPUT
          else
            echo "output.json not present on main — nothing to do."
            echo "removed=false" >> $GITHUB_OUTPUT
          fi

      - name: Note cleanup
        if: steps.clean.outputs.removed == 'true'
        run: echo "Cleaned output.json from main."
