name: Agent Runner

on:
  push:
    paths:
      - 'agent/tasks/queued/*.json'
  workflow_dispatch: {}

jobs:
  run-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt

      - name: Run agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python agent/bot.py

      - name: Create branch and commit changes
        id: commit
        run: |
          BRANCH="agent-$(cat agent/last_branch_name.txt)"

          git config user.name "agent-bot"
          git config user.email "bot@example.com"

          # Make sure we have latest refs
          git fetch origin --prune

          # If branch already exists remotely, delete it to avoid conflicts
          if git ls-remote --exit-code --heads origin "$BRANCH" > /dev/null 2>&1; then
            echo "Remote branch $BRANCH exists; deleting it."
            git push origin --delete "$BRANCH" || true
          fi

          # Create fresh branch from main
          git checkout -B "$BRANCH" origin/main

          git add -A
          if git diff --cached --quiet; then
            echo "no changes"
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          git commit -m "Agent: $(cat agent/last_branch_name.txt)"
          git push --force-with-lease --set-upstream origin "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Open Pull Request
        if: steps.commit.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Agent: $(cat agent/last_branch_name.txt)"
          body: |
            $(cat agent/last_pr_body.txt)
          branch: ${{ steps.commit.outputs.branch }}
          base: main
