name: Agent Runner (PR or Direct)

on:
  push:
    paths:
      - 'agent/tasks/queued/*.json'
  workflow_dispatch: {}

jobs:
  run-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt
          sudo apt-get update
          sudo apt-get install -y jq

      # Detect the first queued task and its mode ("pr" default, or "direct")
      - name: Detect mode and prepare branch or main
        id: prep
        run: |
          TASK_FILE="$(ls agent/tasks/queued/*.json 2>/dev/null | head -n 1 || true)"
          if [ -z "$TASK_FILE" ]; then
            echo "No queued tasks found."
            echo "task=" >> $GITHUB_OUTPUT
            echo "mode=pr" >> $GITHUB_OUTPUT
            echo "branch=" >> $GITHUB_OUTPUT
            exit 0
          fi

          MODE="$(jq -r '.mode // "pr"' "$TASK_FILE")"
          TITLE="$(jq -r '.title // "agent-update"' "$TASK_FILE" | tr '[:space:]' '-' | tr -cd '[:alnum:]-_.')"
          BRANCH="agent-${TITLE}-${GITHUB_RUN_NUMBER}"

          git config user.name "agent-bot"
          git config user.email "bot@example.com"

          git fetch origin --prune
          if [ "$MODE" = "direct" ]; then
            echo "Mode: direct (commit to main)."
            git checkout -B main origin/main
          else
            echo "Mode: pr (commit to branch and open PR)."
            git checkout -B "$BRANCH" origin/main
          fi

          echo "task=$TASK_FILE"   >> $GITHUB_OUTPUT
          echo "mode=$MODE"        >> $GITHUB_OUTPUT
          echo "branch=$BRANCH"    >> $GITHUB_OUTPUT

      - name: Run agent
        if: steps.prep.outputs.task != ''
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python agent/bot.py

      - name: Show repo tree after agent
        if: steps.prep.outputs.task != ''
        run: ls -R

      - name: Print agent outputs
        if: steps.prep.outputs.task != ''
        run: |
          echo "=== last_branch_name ==="
          cat agent/last_branch_name.txt || true
          echo "=== last_pr_body ==="
          cat agent/last_pr_body.txt || true
          echo "=== output.json ==="
          test -f agent/output.json && cat agent/output.json || echo "(no output.json)"

      - name: Commit changes (if any)
        if: steps.prep.outputs.task != ''
        id: commit
        run: |
          # Keep output.json so you can inspect the model response in the PR/commit
          git add agent/output.json || true
          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          COMMIT_MSG="Agent: $(cat agent/last_branch_name.txt 2>/dev/null || echo update)"
          git commit -m "$COMMIT_MSG"

          if [ "${{ steps.prep.outputs.mode }}" = "direct" ]; then
            echo "Pushing directly to main."
            git push origin main
          else
            echo "Pushing to branch: ${{ steps.prep.outputs.branch }}"
            git push --set-upstream origin "${{ steps.prep.outputs.branch }}"
          fi

          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Open Pull Request (PR mode only)
        if: steps.commit.outputs.changed == 'true' && steps.prep.outputs.mode == 'pr'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Agent: $(cat agent/last_branch_name.txt 2>/dev/null || echo update)"
          body: |
            $(cat agent/last_pr_body.txt 2>/dev/null || echo "Agent update")
          branch: ${{ steps.prep.outputs.branch }}
          base: main
