name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer || true
      - name: SwiftLint (placeholder)
        run: echo "Run SwiftLint here"
      - name: Build (placeholder)
        run: echo "xcodebuild build"
      - name: Test (placeholder)
        run: echo "xcodebuild test"
